=== Yelizaryeu/EpamSpringJava/task3/src/main/resources/tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.myelizaryeu.epam.com/tariffs"
        elementFormDefault="qualified">
    <element name="tariffs">
        <complexType>
            <sequence>
                <element name="tariff" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="operator-name" type="string"/>
                            <element name="payroll" type="double"/>
                            <element name="sms-price" type="double"/>
                            <element name="call-prices">
                                <complexType>
                                    <sequence>
                                        <element name="within" type="double"/>
                                        <element name="offline" type="double"/>
                                        <element name="station" type="double"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="parameters">
                                <complexType>
                                    <sequence>
                                        <element name="favorite-numbers">
                                            <simpleType>
                                                <restriction base="int">
                                                    <minInclusive value="0"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="billing">
                                            <simpleType>
                                                <restriction base="string">
                                                    <enumeration value="MINUTE"/>
                                                    <enumeration value="SECONDS"/>
                                                    <enumeration value="TWELVE_SECONDS"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="connection-fee" type="double"/>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" type="ID" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Yelizaryeu/EpamSpringJava/task3/src/main/resources/tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.myelizaryeu.epam.com/tariffs"
         xsi:schemaLocation="http://www.myelizaryeu.epam.com/tariffs tariff.xsd">
    <tariff id="t1">
        <name>Student</name>
        <operator-name>A1</operator-name>
        <payroll>10.8</payroll>
        <sms-price>0.05</sms-price>
        <call-prices>
            <within>0</within>
            <offline>0.5</offline>
            <station>1</station>
        </call-prices>
        <parameters>
            <favorite-numbers>5</favorite-numbers>
            <billing>MINUTE</billing>
            <connection-fee>0</connection-fee>
        </parameters>
    </tariff>
    <tariff id="t2">
        <name>Unlimited</name>
        <operator-name>MTS</operator-name>
        <payroll>22.4</payroll>
        <sms-price>0.001</sms-price>
        <call-prices>
            <within>0</within>
            <offline>0.005</offline>
            <station>0.05</station>
        </call-prices>
        <parameters>
            <favorite-numbers>0</favorite-numbers>
            <billing>TWELVE_SECONDS</billing>
            <connection-fee>5</connection-fee>
        </parameters>
    </tariff>
    <tariff id="t3">
        <name>Affordable</name>
        <operator-name>Life</operator-name>
        <payroll>5</payroll>
        <sms-price>0.005</sms-price>
        <call-prices>
            <within>0.05</within>
            <offline>0.5</offline>
            <station>2</station>
        </call-prices>
        <parameters>
            <favorite-numbers>10</favorite-numbers>
            <billing>SECONDS</billing>
            <connection-fee>0</connection-fee>
        </parameters>
    </tariff>
</tariffs>
